apiVersion: v1
kind: ConfigMap
metadata:
  name: os-service-config
  namespace: default
data:
  NODE_ENV: "production"
  PORT: "3000"
  AWS_REGION: "us-east-1"
  # Database connection ser√° via Secret
