apiVersion: v1
kind: Service
metadata:
  name: os-service
  namespace: default
  labels:
    app: os-service
spec:
  type: ClusterIP
  selector:
    app: os-service
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
